// src/components/MetricCard.vue
<template>
  <div class="ct-card">
    <div class="ct-card-top">
      <span class="ct-card-label">{{ label }}</span>
      <v-icon size="24" :icon="icon" class="ct-card-icon" />
    </div>
    <div class="ct-card-value">{{ value }}</div>
    <div class="ct-card-bar">
      <div class="ct-card-bar-fill"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  label: string;
  value: string;
  icon: string;
}>();
</script>

<style scoped>
.ct-card {
  background: #ffffff;
  border-radius: 14px;
  border: 1px solid #e5e7eb;
  padding: 24px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  box-shadow: 0 4px 12px rgba(15, 23, 42, 0.08);
  transition: box-shadow 0.2s ease;
  height: 100%;
}

.ct-card:hover {
  box-shadow: 0 6px 16px rgba(15, 23, 42, 0.12);
}

.ct-card-top {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.ct-card-label {
  font-size: 10px;
  font-weight: 700;
  color: #9ca3af;
  text-transform: uppercase;
  letter-spacing: 0.12em;
}

.ct-card-icon {
  color: #e2e8f0;
}

.ct-card-value {
  font-size: 56px;
  font-weight: 700;
  color: #1f2937;
  letter-spacing: -0.04em;
  margin: 8px 0;
  font-variant-numeric: tabular-nums;
}

.ct-card-bar {
  width: 100%;
  height: 6px;
  background: #dbeafe;
  border-radius: 999px;
  overflow: hidden;
}

.ct-card-bar-fill {
  height: 100%;
  width: 33%;
  background: #3b82f6;
  transition: width 0.5s ease;
}
</style>

// components/MetricCard.tsx

import React from 'react';
import { LucideIcon } from 'lucide-react';

interface MetricCardProps {
  label: string;
  value: string;
  icon: LucideIcon;
}

const MetricCard: React.FC<MetricCardProps> = ({ label, value, icon: Icon }) => (
  <div className="bg-white rounded-lg border border-gray-200 p-6 flex flex-col justify-between shadow-sm hover:shadow-md transition-shadow h-full">
    <div className="flex justify-between items-start">
      <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">{label}</span>
      <Icon className="w-6 h-6 text-slate-200" />
    </div>
    <div className="text-6xl font-bold text-slate-800 tracking-tighter tabular-nums my-2">
      {value}
    </div>
    <div className="w-full h-1 bg-blue-100 rounded-full overflow-hidden">
      <div className="h-full bg-blue-500 w-1/3 transition-all duration-500"></div>
    </div>
  </div>
);

export default MetricCard;
